apiVersion: v1
kind: PersistentVolume
metadata:
  name: azure-fileshare-pv
spec:
  capacity:
    storage: <YOUR_STORAGE_SIZE>
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  azureFile:
    secretName: azure-secret
    shareName: <YOUR_SHARE_NAME>
    readOnly: false
